---
title: "Education Trends"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(flexdashboard)
library(shiny)
library(ggplot2)
library(waffle)
library(hrbrthemes)
library(r2d3)
library(networkD3)
```



Home {.tabset}
======================



### Relationship Between School Expenditure, Teachers and Education


Compensation {.tabset}
======================

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r}
viz1 <- read_csv("data/viz1.csv")
selectInput("drop1", "Level of Education", 
    unique(viz1$`Level of education`))

```

Column
-----------------------------------------------------------------------

```{r}

selectedData <- reactive({
  viz1 %>%
    filter(`Level of education`==input$drop1)
})

renderPlot({
  viz <- selectedData() %>%
    mutate(comp = paste0(round(staff_comp, 1), "%"))
  ggplot(viz, aes(x = Year, y = staff_comp)) +
    geom_line() +
    geom_label(aes(label = comp, fill = as.factor(Year)),
               show.legend = FALSE) +
    theme_void()
})



renderPlot({
  viz1 <- selectedData() %>%
    mutate(Year = as.factor(Year)) %>%
    mutate(Teacher = round(Teacher/1000)) %>%
    mutate(comp = paste0(round(staff_comp, 1), "%"))
  viz1 %>%
    count(Year, wt = Teacher) %>%
    ggplot(aes(fill = Year, values = n)) +
    geom_waffle(
      n_rows = 6, color = "white", show.legend = FALSE, flip = TRUE) +
    facet_wrap(~Year, ncol = 6) +
    theme(panel.spacing.x = unit(0, "npc"),
          panel.background = NULL,
          axis.ticks.length = unit(0, "npc"),
          panel.grid = element_line(colour = "white")) +
    theme_enhance_waffle() +
    theme_void()
  
})

```


Enrollment
======================

Inputs {.sidebar}
-----------------------------------------------------------------------




Column {.tabset}
-------------------------------------

### 2014

```{r}
addResourcePath("tmpuser", getwd())

renderUI({
      tags$iframe(seamless="seamless", 
                  src= "tmpuser/viz2_2014.html",
                  width=1200, 
                  height=800)
     })
```


### 2015

```{r}
addResourcePath("tmpuser", getwd())

renderUI({
      tags$iframe(seamless="seamless", 
                  src= "tmpuser/viz2_2015.html",
                  width=1200, 
                  height=800)
     })
```


### 2016

```{r}
addResourcePath("tmpuser", getwd())

renderUI({
      tags$iframe(seamless="seamless", 
                  src= "tmpuser/viz2_2016.html",
                  width=1200, 
                  height=800)
     })
```

### 2017

```{r}
addResourcePath("tmpuser", getwd())

renderUI({
      tags$iframe(seamless="seamless", 
                  src= "tmpuser/viz2_2017.html",
                  width=1200, 
                  height=800)
     })
```


### 2018

```{r}
addResourcePath("tmpuser", getwd())

renderUI({
      tags$iframe(seamless="seamless", 
                  src= "tmpuser/viz2_2018.html",
                  width=1200, 
                  height=800)
     })
```

Teacher:Student Ratio
======================

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
viz3 <- read_csv("data/viz3.csv")
selectInput("drop3", "Year", 
    unique(viz3$Year))

```


Column {.tabset}
-------------------------------------

```{r}

selectedData2 <- reactive({
  viz3 %>%
    filter(Year == as.numeric(input$drop3))
})

renderSankeyNetwork({
  Nodes <- data.frame(numbers = c("H", "UM", "LM", "L",
                                  unique(selectedData2()$Country)))
  my_color <- 'd3.scaleOrdinal()
  .domain(["H", "UM","LM", "L"])
  .range(["#D98C00", "#D4ECDD" , "#A7C5EB", "#E9896A"])'
  links <- selectedData2() %>%
    select(income, Country, student_to_1_teacher) %>%
    mutate(source = recode(income, H = 0, UM = 1, LM = 2, L = 3)) %>%
    rowwise() %>%
    mutate(Country = which(Nodes == Country)-1) %>%
    distinct(Country, .keep_all = TRUE)
  
  check <- sankeyNetwork(Links = links, Nodes = Nodes, Source = "source",
              Target = "Country", Value = "student_to_1_teacher",
              NodeID = "numbers", units = " students", fontSize = 15, nodeWidth = 25,
              LinkGroup = "income", colourScale=my_color)
  check
})
  
```


